import React, { useState } from 'react'
import ReactDOM from 'react-dom/client'
import { QueryClient, QueryClientProvider, useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { BrowserRouter, NavLink, Route, Routes } from 'react-router-dom'
import { Alert, App as AntApp, Button, Card, ConfigProvider, Form, Input, InputNumber, Layout, Menu, Modal, Select, Space, Statistic, Switch, Table, Tag, Typography, message, theme } from 'antd'
import './styles.css'

const queryClient = new QueryClient()
let csrf = ''

async function api(path: string, options: RequestInit = {}) {
  const headers = new Headers(options.headers)
  if (options.body) headers.set('Content-Type', 'application/json')
  if (!['GET', 'HEAD'].includes(options.method || 'GET') && csrf) headers.set('X-CSRF-Token', csrf)
  const response = await fetch(path, {...options, headers, credentials: 'same-origin'})
  if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.detail?.message || body.detail || `HTTP ${response.status}`) }
  return response.json()
}

function Auth({children}: {children: React.ReactNode}) {
  const status = useQuery({queryKey: ['auth'], queryFn: () => api('/auth/status')})
  if (status.isLoading) return <div className="center">Loading…</div>
  if (status.data?.authenticated) { csrf = status.data.csrfToken; return children }
  const setup = !status.data?.initialized
  return <div className="auth"><Card title={setup ? 'Create Administrator' : 'Sign in'}><Typography.Paragraph type="secondary">TrafficManager</Typography.Paragraph><Form layout="vertical" onFinish={async values => {try {const result = await api(setup ? '/auth/setup' : '/auth/login', {method:'POST', body:JSON.stringify(values)}); csrf=result.csrfToken; await status.refetch()} catch(e) {message.error(String(e))}}}><Form.Item name="username" label="Username" rules={[{required:true}]}><Input autoFocus/></Form.Item><Form.Item name="password" label="Password" rules={[{required:true,min:10}]}><Input.Password/></Form.Item><Button block type="primary" htmlType="submit">{setup ? 'Create administrator' : 'Sign in'}</Button></Form></Card></div>
}

const fmt = (n?: number | null) => n == null ? '—' : n === 0 ? 'Unlimited' : `${(n / 1073741824).toFixed(n > 10737418240 ? 0 : 1)} GiB`
const statusTag = (value: string) => <Tag color={value === 'ONLINE' || value === 'SUCCESS' ? 'green' : value === 'OBSERVE' || value === 'PARTIAL' ? 'gold' : value === 'MANAGED' ? 'blue' : 'red'}>{value}</Tag>

function Dashboard() {
  const {data = {}} = useQuery({queryKey:['dashboard'],queryFn:()=>api('/api/dashboard'),refetchInterval:15000})
  const cards = [['Nodes',data.nodes],['Online',data.online_nodes],['Clients',data.clients],['Managed',data.managed_clients],['Policy conflicts',data.policy_conflicts],['Near quota',data.near_quota_clients],['Failed jobs',data.failed_jobs],['Total traffic',fmt(data.total_traffic)]]
  return <><Typography.Title level={2}>Dashboard</Typography.Title><div className="grid">{cards.map(([title,value])=><Card key={title as string}><Statistic title={title} value={value ?? 0}/></Card>)}</div></>
}

function Nodes() {
  const qc=useQueryClient(), {data=[]}=useQuery({queryKey:['nodes'],queryFn:()=>api('/api/nodes')}); const [open,setOpen]=useState(false); const [form]=Form.useForm()
  const add=useMutation({mutationFn:(v:any)=>api('/api/nodes',{method:'POST',body:JSON.stringify(v)}),onSuccess:()=>{message.success('Node added; initial sync started');setOpen(false);form.resetFields();qc.invalidateQueries({queryKey:['nodes']})},onError:e=>message.error(String(e))})
  return <><Space className="heading"><Typography.Title level={2}>Nodes</Typography.Title><Button type="primary" onClick={()=>setOpen(true)}>Add node</Button></Space><Table rowKey="id" dataSource={data} columns={[{title:'Status',dataIndex:'status',render:statusTag},{title:'Name',dataIndex:'name'},{title:'Remark',dataIndex:'remark'},{title:'Base URL',dataIndex:'base_url'},{title:'API',dataIndex:'api_mode'},{title:'Inbounds',dataIndex:'inbounds'},{title:'Clients',dataIndex:'clients'},{title:'TLS',dataIndex:'tls_verify',render:v=>v?<Tag color="green">Verified</Tag>:<Tag color="red">Skipped</Tag>},{title:'Actions',render:(_,r:any)=><Button onClick={async()=>{try{await api(`/api/nodes/${r.id}/sync`,{method:'POST'});message.success('Sync complete');qc.invalidateQueries()}catch(e){message.error(String(e))}}}>Sync</Button>}]}/><Modal title="Add 3x-ui node" open={open} onCancel={()=>setOpen(false)} onOk={()=>form.submit()} confirmLoading={add.isPending}><Alert type="info" showIcon message="The node is tested before it is saved. The token is encrypted and never returned."/><Form form={form} layout="vertical" onFinish={v=>add.mutate({...v,tags:[],tls_verify:v.tls_verify??true})}><Form.Item name="name" label="Name" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="remark" label="Remark"><Input/></Form.Item><Form.Item name="base_url" label="Base URL" rules={[{required:true}]}><Input placeholder="https://host:2053/webbase"/></Form.Item><Form.Item name="token" label="API token" rules={[{required:true}]}><Input.Password/></Form.Item><Form.Item name="tls_verify" label="Verify TLS" valuePropName="checked" initialValue={true}><Switch/></Form.Item></Form></Modal></>
}

function Clients() {
  const qc=useQueryClient(), {data=[]}=useQuery({queryKey:['clients'],queryFn:()=>api('/api/clients')}); const [selected,setSelected]=useState<React.Key[]>([])
  const reset=async(start=false)=>{const ids=selected.map(Number);const p=await api('/api/clients/reset-preview',{method:'POST',body:JSON.stringify({client_ids:ids,start_new_cycle:start})});Modal.confirm({title:start?'Start new cycle':'Reset traffic',content:<div><p>Targets: {p.nodes} nodes, {p.inbounds} inbounds, {p.clients} clients</p><p>Inbound aggregate counters: no change</p><p>This cannot restore old traffic counters.</p></div>,okText:`Confirm ${p.clients} clients`,okType:'danger',onOk:async()=>{const result=await api('/api/clients/bulk-reset',{method:'POST',body:JSON.stringify({client_ids:ids,start_new_cycle:start})});message.success(`Job #${result.job_id} started`)}})}
  return <><Space className="heading"><Typography.Title level={2}>Clients</Typography.Title><Button disabled={!selected.length} danger onClick={()=>reset(false)}>Reset traffic</Button><Button disabled={!selected.length} type="primary" onClick={()=>reset(true)}>Start new cycle</Button></Space><Table rowKey="id" rowSelection={{selectedRowKeys:selected,onChange:setSelected}} dataSource={data} columns={[{title:'Node',dataIndex:'node'},{title:'Email',dataIndex:'email'},{title:'Inbounds',dataIndex:'inbounds',render:v=>v.map((x:any)=>x.remark||x.remote_id).join(', ')},{title:'Mode',dataIndex:'managed_mode',render:(v,r:any)=><Select value={v} style={{width:120}} options={['MANAGED','OBSERVE','IGNORE'].map(x=>({value:x}))} onChange={async mode=>{await api(`/api/clients/${r.id}`,{method:'PATCH',body:JSON.stringify({managed_mode:mode})});qc.invalidateQueries({queryKey:['clients']})}}/>},{title:'Used',dataIndex:'used_bytes',render:fmt},{title:'Quota',dataIndex:'quota_bytes',render:fmt},{title:'Usage',dataIndex:'percentage',render:v=>v==null?'—':`${v}%`},{title:'Effective policy',dataIndex:'policy',render:(v,r:any)=>r.policy_conflict?<Tag color="gold">Policy Conflict</Tag>:v||'None'},{title:'Warnings',render:(_,r:any)=>r.native_reset_conflict?<Tag color="gold">Native Reset Conflict</Tag>:null}]}/></>
}

function Policies() {
  const qc=useQueryClient(),{data=[]}=useQuery({queryKey:['policies'],queryFn:()=>api('/api/policies')});const [open,setOpen]=useState(false);const [form]=Form.useForm()
  const create=async(v:any)=>{try{await api('/api/policies',{method:'POST',body:JSON.stringify({...v,quota_bytes:v.unlimited?null:Number(v.quota_gib)*1073741824,local_time:v.local_time||'00:00',enabled:true,reset_enabled:v.reset_enabled??true,catchup_enabled:true,catchup_max_hours:168,missing_day_policy:'LAST_DAY',reactivate_mode:'PRESERVE'})});message.success('Policy created');setOpen(false);form.resetFields();qc.invalidateQueries({queryKey:['policies']})}catch(e){message.error(String(e))}}
  return <><Space className="heading"><Typography.Title level={2}>Policies</Typography.Title><Button type="primary" onClick={()=>setOpen(true)}>Create policy</Button></Space><Table rowKey="id" dataSource={data} columns={[{title:'Name',dataIndex:'name'},{title:'Quota',dataIndex:'quota_bytes',render:fmt},{title:'Schedule',render:(_,r:any)=>r.reset_enabled?`Day ${r.monthly_day} at ${r.local_time}`:'Disabled'},{title:'Timezone',dataIndex:'timezone'},{title:'Next run',dataIndex:'next_run_at',render:v=>v?new Date(v).toLocaleString():'—'},{title:'Enabled',dataIndex:'enabled',render:v=>v?<Tag color="green">Yes</Tag>:'No'}]}/><Modal title="Create policy" open={open} onCancel={()=>setOpen(false)} onOk={()=>form.submit()}><Form form={form} layout="vertical" onFinish={create}><Form.Item name="name" label="Name" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="quota_gib" label="Quota (GiB, blank for unlimited)"><InputNumber min={0} precision={0} style={{width:'100%'}}/></Form.Item><Form.Item name="reset_enabled" label="Monthly reset" valuePropName="checked" initialValue={true}><Switch/></Form.Item><Form.Item name="monthly_day" label="Day" initialValue={1}><InputNumber min={1} max={31}/></Form.Item><Form.Item name="local_time" label="Local time" initialValue="00:00"><Input type="time"/></Form.Item><Form.Item name="timezone" label="IANA timezone" initialValue="UTC"><Select showSearch options={['UTC','Asia/Shanghai','Asia/Tokyo','America/New_York','America/Los_Angeles','Europe/London','Europe/Berlin'].map(value=>({value}))}/></Form.Item></Form></Modal></>
}

function Jobs(){const{data=[]}=useQuery({queryKey:['jobs'],queryFn:()=>api('/api/jobs'),refetchInterval:5000});return <><Typography.Title level={2}>Jobs</Typography.Title><Table rowKey="id" dataSource={data} columns={[{title:'ID',dataIndex:'id'},{title:'Type',dataIndex:'type'},{title:'Source',dataIndex:'source'},{title:'Status',dataIndex:'status',render:statusTag},{title:'Targets',dataIndex:'total_targets'},{title:'Success',dataIndex:'success_count'},{title:'Failed',dataIndex:'failure_count'},{title:'Created',dataIndex:'created_at',render:v=>new Date(v).toLocaleString()},{title:'Summary',dataIndex:'summary'}]}/></>}
function Audit(){const{data=[]}=useQuery({queryKey:['audit'],queryFn:()=>api('/api/audit')});return <><Typography.Title level={2}>Audit Log</Typography.Title><Table rowKey="id" dataSource={data} columns={[{title:'Time',dataIndex:'timestamp',render:v=>new Date(v).toLocaleString()},{title:'Actor',dataIndex:'actor'},{title:'Source',dataIndex:'source'},{title:'Action',dataIndex:'action'},{title:'Target',dataIndex:'target'},{title:'Result',dataIndex:'result',render:statusTag}]}/></>}
function Settings(){const{data={}}=useQuery({queryKey:['settings'],queryFn:()=>api('/api/settings')});return <><Typography.Title level={2}>Settings</Typography.Title><Card><Typography.Title level={4}>General & Jobs</Typography.Title><p>Sync interval: {data.sync_interval_minutes} minutes</p><p>UI timezone: {data.default_ui_timezone}</p><p>Concurrency: {data.global_concurrency} global / {data.per_node_concurrency} per node</p><p>Network retries: {data.network_retries}; verify retries: {data.verify_retries}</p><Button href="/api/settings/backup">Download database backup</Button></Card></>}

const entries=[['/','Dashboard'],['/nodes','Nodes'],['/clients','Clients'],['/policies','Policies'],['/jobs','Jobs'],['/audit','Audit Log'],['/settings','Settings']]
function Shell(){const[dark,setDark]=useState(false);return <ConfigProvider theme={{algorithm:dark?theme.darkAlgorithm:theme.defaultAlgorithm}}><Layout className="shell"><Layout.Sider breakpoint="lg" collapsedWidth="0"><div className="brand">TrafficManager<br/><small>3x-ui traffic control</small></div><Menu theme="dark" mode="inline" items={entries.map(([key,label])=>({key,label:<NavLink to={key}>{label}</NavLink>}))}/></Layout.Sider><Layout><Layout.Header className="top"><Typography.Text>Centralized Traffic Policy & Reset Management</Typography.Text><Switch checkedChildren="Dark" unCheckedChildren="Light" checked={dark} onChange={setDark}/></Layout.Header><Layout.Content className="content"><Routes><Route path="/" element={<Dashboard/>}/><Route path="/nodes" element={<Nodes/>}/><Route path="/clients" element={<Clients/>}/><Route path="/policies" element={<Policies/>}/><Route path="/jobs" element={<Jobs/>}/><Route path="/audit" element={<Audit/>}/><Route path="/settings" element={<Settings/>}/></Routes></Layout.Content></Layout></Layout></ConfigProvider>}
function Root(){return <AntApp><QueryClientProvider client={queryClient}><BrowserRouter><Auth><Shell/></Auth></BrowserRouter></QueryClientProvider></AntApp>}
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><Root/></React.StrictMode>)
